import {
  ContactFormData,
  RedtailContactRec,
  RedtailSettingsData,
} from "../interfaces/redtail.interface";
import { v4 as uuid } from "uuid";

export const createEmptyContactRefData = (): Readonly<RedtailContactRec> =>
  Object.freeze({
    Address: null,
    ContactRecord: {
      Age: 0,
      AnniversaryDate: "",
      Category: "",
      CategoryID: 0,
      ClientID: 0,
      ClientSince: "",
      ClientSinceDate: "",
      ClientType: "",
      Company: "",
      CompanyID: 0,
      DatabaseID: 0,
      DateOfBirth: "",
      Deceased: "",
      Deleted: false,
      DeletedOn: "",
      Designation: "",
      Family: false,
      FamilyHeadID: 0,
      Familyname: "",
      Firstname: "",
      Gender: "",
      InputBy: null,
      InputByID: 0,
      InputDate: "",
      JobTitle: "",
      LastUpdate: "",
      Lastname: "",
      MaritalDate: "",
      MaritalStatus: "",
      Middlename: "",
      Name: "",
      Nickname: "",
      ReferredBy: "",
      Relationship: null,
      Salutation: "",
      ServicingAdvisor: "",
      ServicingAdvisorID: 0,
      Source: "",
      SourceID: 0,
      Status: "",
      StatusID: 0,
      Suffix: "",
      TaxID: "",
      WritingAdvisor: "",
      WritingAdvisorID: 0,
    },
    Internet: null,
    Phone: null,
  });

export const createEmptyFormData = (): Readonly<ContactFormData> =>
  Object.freeze({
    key: uuid(),
    salutation: "",
    firstName: "",
    middleName: "",
    lastName: "",
    nickname: "",
    dateOfBirth: null,
    gender: "",
    categoryID: 0,
    statusID: 0,
    sourceID: 0,
    taxID: "",
    servicingAdvisorID: 0,
    writingAdvisorID: 0,
    phoneNumbers: [
      {
        key: uuid(),
        recID: 0,
        phoneNumber: "",
        typeID: "",
        primaryPhone: false,
      },
    ],
    emailAddresses: [
      {
        key: uuid(),
        recID: 0,
        emailAddress: "",
        typeID: 0,
        primaryEmail: false,
      },
    ],
    streetAddresses: [
      {
        key: uuid(),
        recID: 0,
        streetAddress: "",
        secondaryAddress: "",
        city: "",
        state: "",
        zip: "",
        typeID: "",
        primaryStreet: false,
      },
    ],
  });

export const createEmptyDropDownData = (): Readonly<RedtailSettingsData> =>
  Object.freeze({
    statuses: [],
    categories: [],
    sources: [],
    salutations: [],
    servicingAdvisors: [],
    writingAdvisors: [],
    gender: [],
    addressTypes: [],
    internetTypes: [],
    phoneTypes: [],
  });
